Lesson 1
Task 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np. Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.



In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3,3,1],[6,8,11,10,7]])

In [3]:
A.transpose()

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
np.mean(A, axis=1)

array([2. , 8.4])

In [5]:
mean_a = np.array([2. , 8.4])


In [6]:
print(mean_a)

[2.  8.4]


Task 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [29]:
a_centered = A.transpose() - mean_a

In [30]:
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


Task 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [33]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]

In [34]:
print(a_centered_sp)

8.0


In [48]:
N = a_centered.shape[0] - 1

In [49]:
print(N)

4


In [50]:
a_centered_sp / N

2.0

Task 4

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [51]:
np.cov(A.T)

array([[12.5, 15. , 20. , 17.5, 15. ],
       [15. , 18. , 24. , 21. , 18. ],
       [20. , 24. , 32. , 28. , 24. ],
       [17.5, 21. , 28. , 24.5, 21. ],
       [15. , 18. , 24. , 21. , 18. ]])

In [59]:
np.cov(A.T)[0, 1]

15.0

In [60]:
np.cov(A)[0, 1]

2.0

In [61]:
np.cov(A)

array([[1. , 2. ],
       [2. , 4.3]])